apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ds4v9jeby-python 
  janus-idp.io/tekton: ds4v9jeby-python
  backstage.io/kubernetes-id: ds4v9jeby-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ds4v9jeby-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  