apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ds4v9jeby-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds4v9jeby-python 
  name: ds4v9jeby-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ds4v9jeby-python 
